# Use the official OpenJDK 17 Alpine image as the base image
#FROM adoptopenjdk/openjdk17:alpine-slim
FROM openjdk:17-jdk-slim
# Set the working directory inside the container
WORKDIR /app

# Copy the packaged JAR file into the container at /app
COPY target/blog-0.0.1-SNAPSHOT.jar /app/blog-0.0.1-SNAPSHOT.jar

# Expose the port that your Spring Boot application runs on
EXPOSE 8080

# Specify the command to run your Spring Boot application when the container starts
CMD ["java", "-jar", "blog-0.0.1-SNAPSHOT.jar"]
