# pull official base image
FROM node:14-alpine AS build-stage

# set working directory
WORKDIR /app


# install app dependencies
COPY package.json .
COPY package-lock.json ./
RUN npm install

COPY . .



EXPOSE 3000

# start app
CMD ["npm", "start"]